/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author PCB
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Loginbtn.setBorderPainted(false);
        kButton1.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loginbtn = new com.k33ptoo.components.KButton();
        jLabel8 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(173, 46, 54));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1045, 559));
        setMinimumSize(new java.awt.Dimension(1045, 559));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1045, 559));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(37, 37, 37));
        jPanel1.setMaximumSize(new java.awt.Dimension(1045, 559));
        jPanel1.setMinimumSize(new java.awt.Dimension(1045, 559));
        jPanel1.setPreferredSize(new java.awt.Dimension(1045, 559));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loginbtn.setForeground(new java.awt.Color(51, 51, 51));
        Loginbtn.setText("Login");
        Loginbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Loginbtn.setkAllowGradient(false);
        Loginbtn.setkBackGroundColor(new java.awt.Color(242, 237, 229));
        Loginbtn.setkBorderRadius(50);
        Loginbtn.setkForeGround(new java.awt.Color(51, 51, 51));
        Loginbtn.setkHoverColor(new java.awt.Color(51, 51, 51));
        Loginbtn.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        Loginbtn.setkPressedColor(new java.awt.Color(51, 51, 51));
        Loginbtn.setkSelectedColor(new java.awt.Color(102, 102, 102));
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 170, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/anteiku.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        kButton1.setkAllowGradient(false);
        kButton1.setkBackGroundColor(new java.awt.Color(229, 199, 137));
        kButton1.setkBorderRadius(400);
        kButton1.setkEndColor(new java.awt.Color(229, 199, 137));
        kButton1.setkForeGround(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverColor(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverEndColor(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverForeGround(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverStartColor(new java.awt.Color(229, 199, 137));
        kButton1.setkIndicatorColor(new java.awt.Color(229, 199, 137));
        kButton1.setkPressedColor(new java.awt.Color(229, 199, 137));
        kButton1.setkSelectedColor(new java.awt.Color(229, 199, 137));
        kButton1.setkStartColor(new java.awt.Color(229, 199, 137));
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 410, 370));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        Passwordtxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Passwordtxt.setForeground(new java.awt.Color(204, 204, 204));
        Passwordtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        Passwordtxt.setOpaque(false);
        Passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordtxtActionPerformed(evt);
            }
        });
        jPanel1.add(Passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 266, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        Usernametxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Usernametxt.setForeground(new java.awt.Color(204, 204, 204));
        Usernametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        Usernametxt.setOpaque(false);
        Usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametxtActionPerformed(evt);
            }
        });
        jPanel1.add(Usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 266, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/useraaaaaaaaa.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lastloginsa.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 700, 580));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/61457aaaaaaa.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Anteiku");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 180, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordtxtActionPerformed

    private void UsernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametxtActionPerformed

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // TODO add your handling code here:
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-AQ0ITDE\\MSSQLSERVER;databaseName=RMSproject;user=admin;password=root;encrypt=true;trustServerCertificate=true;";
            Connection con = DriverManager.getConnection(connectionUrl);

            String username = Usernametxt.getText();
            String password = Passwordtxt.getText();

            Statement stm = con.createStatement();
            String sql = "select * from admin_login where Username='"+username+"' and Passwords='"+password+"'";
            ResultSet rs = stm.executeQuery(sql);

            if(rs.next()){

                dispose();
                Order ord = new Order();
                ord.show();
            }
            else{
                JOptionPane.showMessageDialog(this,"Error logging in! \n please check your username and password.");
                Usernametxt.setText("");
                Passwordtxt.setText("");
            }
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Loginbtn;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton1;
    // End of variables declaration//GEN-END:variables

}
