/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCB
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public Sales() {
        initComponents();
        AdminTable();
        burrons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salestbl = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        Logoutbtn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Orderbtn = new com.k33ptoo.components.KButton();
        Salesbtn = new com.k33ptoo.components.KButton();
        Adminbtn = new com.k33ptoo.components.KButton();
        Userbtn = new com.k33ptoo.components.KButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1560, 920));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase History");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        Salestbl.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Salestbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Food ID", "Food Name", "Customer ID", "Admin ID", "Reference Number", "Order Date", "Order Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Salestbl.setRequestFocusEnabled(false);
        Salestbl.setRowHeight(20);
        jScrollPane1.setViewportView(Salestbl);
        if (Salestbl.getColumnModel().getColumnCount() > 0) {
            Salestbl.getColumnModel().getColumn(0).setResizable(false);
            Salestbl.getColumnModel().getColumn(1).setResizable(false);
            Salestbl.getColumnModel().getColumn(2).setResizable(false);
            Salestbl.getColumnModel().getColumn(3).setResizable(false);
            Salestbl.getColumnModel().getColumn(4).setResizable(false);
            Salestbl.getColumnModel().getColumn(5).setResizable(false);
            Salestbl.getColumnModel().getColumn(6).setResizable(false);
            Salestbl.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 1070, 550));

        jLabel10.setBackground(new java.awt.Color(52, 52, 52));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(52, 52, 52));
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/anteikusmol.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        kButton1.setkAllowGradient(false);
        kButton1.setkBackGroundColor(new java.awt.Color(229, 199, 137));
        kButton1.setkBorderRadius(400);
        kButton1.setkEndColor(new java.awt.Color(229, 199, 137));
        kButton1.setkForeGround(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverColor(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverEndColor(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverForeGround(new java.awt.Color(229, 199, 137));
        kButton1.setkHoverStartColor(new java.awt.Color(229, 199, 137));
        kButton1.setkIndicatorColor(new java.awt.Color(229, 199, 137));
        kButton1.setkPressedColor(new java.awt.Color(229, 199, 137));
        kButton1.setkSelectedColor(new java.awt.Color(229, 199, 137));
        kButton1.setkStartColor(new java.awt.Color(229, 199, 137));
        getContentPane().add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 100));

        Logoutbtn.setBackground(new java.awt.Color(52, 52, 52));
        Logoutbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(52, 52, 52));
        Logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-out-icon-27res_1.png"))); // NOI18N
        Logoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 860, -1, -1));

        jPanel5.setBackground(new java.awt.Color(52, 52, 52));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Orderbtn.setBackground(new java.awt.Color(52, 52, 52));
        Orderbtn.setText("ORDER");
        Orderbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Orderbtn.setkAllowGradient(false);
        Orderbtn.setkBackGroundColor(new java.awt.Color(52, 52, 52));
        Orderbtn.setkBorderRadius(30);
        Orderbtn.setkForeGround(new java.awt.Color(240, 240, 240));
        Orderbtn.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        Orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Orderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, -1));

        Salesbtn.setBackground(new java.awt.Color(52, 52, 52));
        Salesbtn.setForeground(new java.awt.Color(52, 52, 52));
        Salesbtn.setText("SALES");
        Salesbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Salesbtn.setkAllowGradient(false);
        Salesbtn.setkAllowTab(true);
        Salesbtn.setkBackGroundColor(new java.awt.Color(240, 240, 240));
        Salesbtn.setkBorderRadius(30);
        Salesbtn.setkForeGround(new java.awt.Color(51, 51, 51));
        Salesbtn.setkHoverColor(new java.awt.Color(240, 240, 240));
        Salesbtn.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        Salesbtn.setkHoverStartColor(new java.awt.Color(240, 240, 240));
        Salesbtn.setkSelectedColor(new java.awt.Color(240, 240, 240));
        Salesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Salesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 170, -1));

        Adminbtn.setBackground(new java.awt.Color(52, 52, 52));
        Adminbtn.setText("EDIT ADMIN");
        Adminbtn.setActionCommand("ORDER");
        Adminbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Adminbtn.setkAllowGradient(false);
        Adminbtn.setkBackGroundColor(new java.awt.Color(52, 52, 52));
        Adminbtn.setkBorderRadius(30);
        Adminbtn.setkForeGround(new java.awt.Color(240, 240, 240));
        Adminbtn.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        Adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Adminbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, -1));

        Userbtn.setBackground(new java.awt.Color(52, 52, 52));
        Userbtn.setText("EDIT USER");
        Userbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Userbtn.setkAllowGradient(false);
        Userbtn.setkBackGroundColor(new java.awt.Color(52, 52, 52));
        Userbtn.setkBorderRadius(30);
        Userbtn.setkForeGround(new java.awt.Color(240, 240, 240));
        Userbtn.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        Userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 170, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 920));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgyea.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesbtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SalesbtnActionPerformed

    private void OrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        Order ord = new Order();
        ord.show();
    }//GEN-LAST:event_OrderbtnActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void LogoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseClicked
        // TODO add your handling code here:
        dispose();
        Login log = new Login();
        log.show();
    }//GEN-LAST:event_LogoutbtnMouseClicked

    private void UserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        User us = new User();
        us.show();
    }//GEN-LAST:event_UserbtnActionPerformed

    private void AdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin a = new Admin();
        a.show();   
    }//GEN-LAST:event_AdminbtnActionPerformed

    public void AdminTable(){
    try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-AQ0ITDE\\MSSQLSERVER;databaseName=RMSproject;user=admin;password=root;encrypt=true;trustServerCertificate=true;";
            Connection con = DriverManager.getConnection(connectionUrl);

            Statement stm = con.createStatement();
            String sql = "select OrderID , o.FoodID, f.Product_Name 'Food Name' ,CustomerID,AdminID, ReferenceNum, OrderDate, OrderTime from Orders as o left join FoodItem f on o.FoodID = f.FoodID";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()){
                String OrderID = String.valueOf(rs.getInt("OrderId"));
                String FoodID = rs.getString("FoodID");
                String FoodName = rs.getString("Food Name");
                String CustomID = rs.getString("CustomerID");
                String AdminID = rs.getString("AdminID");
                String ReferenceNum = rs.getString("ReferenceNum");
                String OrderDate = rs.getString("OrderDate");
                String OrderTime = rs.getString("OrderTime");
                
                String tbData[] = {OrderID,FoodID,FoodName,CustomID,AdminID,ReferenceNum,OrderDate,OrderTime};
                DefaultTableModel tblModel = (DefaultTableModel)Salestbl.getModel();
                tblModel.addRow(tbData);
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
}
        public void burrons(){
        Orderbtn.setBorderPainted(false);
        Userbtn.setBorderPainted(false);
        Adminbtn.setBorderPainted(false);
        Salesbtn.setBorderPainted(false);
        kButton1.setBorderPainted(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Adminbtn;
    private javax.swing.JLabel Logoutbtn;
    private com.k33ptoo.components.KButton Orderbtn;
    private com.k33ptoo.components.KButton Salesbtn;
    private javax.swing.JTable Salestbl;
    private com.k33ptoo.components.KButton Userbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton1;
    // End of variables declaration//GEN-END:variables
}
